// Pure TypeScript — no framework imports
// Source: core/ui-kit/angular/src/lib/helpers/icon.helper.ts (type only — SVG map in P0.2)

export const ICON_NAMES = [
  "user",
  "envelope",
  "phone",
  "lock",
  "search",
  "eye",
  "eyeSlash",
  "calendar",
  "shieldCheck",
  "checkCircle",
  "briefcase",
  "documentText",
  "cog",
  "trash",
  "plus",
  "bold",
  "italic",
  "underline",
  "strikethrough",
  "subscript",
  "superscript",
  "fontColor",
  "highlight",
  "listBullet",
  "listOrdered",
  "undo",
  "redo",
  "code",
  "inlineCode",
  "alignLeft",
  "alignCenter",
  "alignRight",
  "alignJustify",
  "indent",
  "outdent",
  "language",
  "magic",
  "layers",
  "tag",
  "percent",
  "cursor",
  "chevronRight",
  "calculator",
  "menu",
  "chevronDown",
  "refresh",
  "pdf",
  "print",
  "excel",
  "youtube",
  "grid",
  "users",
  "package",
  "save",
  "clear",
  "close",
  "externalLink",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
