import type { ReactNode } from 'react';

import type { Intent, BaseProps } from '../types';

/** Position of the toast container on screen. */
export type ToastPosition =
  | 'top-right'
  | 'top-left'
  | 'bottom-right'
  | 'bottom-left'
  | 'top-center'
  | 'bottom-center';

/** Optional action button rendered inside a toast. */
export interface ToastAction {
  label: string;
  onClick: () => void;
}

/** Data shape for a single toast notification. */
export interface ToastItemData {
  /** Unique identifier (auto-generated by ToastProvider). */
  id: string;
  /** Semantic color intent. @default 'default' */
  intent?: Intent;
  /** Bold heading line. */
  title: string;
  /** Optional body text below the title. */
  message?: string;
  /**
   * Auto-dismiss duration in ms. 0 = persistent.
   * @default 4000
   */
  duration?: number;
  /** Optional action button. */
  action?: ToastAction;
}

/** Props for the single Toast item component. */
export interface ToastProps extends BaseProps {
  toast: ToastItemData;
  onDismiss: (id: string) => void;
}

/** Props for the ToastProvider. */
export interface ToastProviderProps {
  children: ReactNode;
  /** Where on screen to render toasts. @default 'top-right' */
  position?: ToastPosition;
  /**
   * Maximum number of toasts shown at once (oldest are removed).
   * @default 5
   */
  maxToasts?: number;
}

/** Value exposed by ToastContext / useToast(). */
export interface ToastContextValue {
  /** Add a toast; returns its generated id. */
  show: (toast: Omit<ToastItemData, 'id'>) => string;
  /** Remove a toast by id. */
  dismiss: (id: string) => void;
  /** Remove all toasts. */
  dismissAll: () => void;
  /** Current toast list (read-only). */
  toasts: ToastItemData[];
  /** Active container position. */
  position: ToastPosition;
}
